### ISSUE TITLE
Hangs during world generation (spawn point) when with other mods

### ISSUE THREAD

**Issue by Flabort** [Zkaface/TAIGA#79]
I have no idea why, but the new world generation features in this mod refuse to play nicely with other mods I've been looking at.

I know for sure it doesn't work when the following collection of mods is installed:
YUNoMakeGoodMap, JEI, Just Enough Resources, Armory, Armory - Weaponry, Tinkers Construct, Tinkers Addons, WAILA, and WAILA Harvestibility. These are on 1.10.2.
I'm not sure which of these mods it's hanging with, but the console says "Preparing spawn area for level 0", and no matter how long you wait it never loads. Removing this mod and only this mod fixed it. 

It's a shame, the new ores and alloys in this look really good and I would have liked them in my pack.

**Comment by Zkaface** [comment]
@Flabort I push out an update this evening. I can not guarantee, that it will fix it, but I changed several things in ore generation. Maybe there is an endless loop.

**Comment by Zkaface** [comment]
Should be fixed. Please report /reopen again, If not!

**Comment by Flabort** [comment]
I just tested with YUNoMakeGoodMap, it's definitely still not working if both this and that mod are present, but it might be an issue with their mod.

**Comment by Zkaface** [comment]
@Flabort OK, could probably be the problem, that my mod has an extensive generation for ores. Like meteorites and the search for lava in each chunk.
